#!/usr/bin/env python3
"""Stage 7 — upsert out/cards.json into the Supabase `cards` table.

Keyed on card_id (stored in the `slug`/`card_id` columns, both unique) so
re-runs UPDATE instead of duplicating. Every value is sanitized first.

The anon key is read-only (RLS), so this script does NOT write directly: it
computes the insert-vs-update split (reading existing slugs with the anon key)
and EMITS an idempotent upsert to out/upsert.sql. The SQL is then applied with
elevated access (Supabase MCP / service role).

  python load.py            # dry-run: report counts + write out/upsert.sql
  python load.py --report   # just print the insert/update split
"""
from __future__ import annotations
import argparse
import json
import sys

import requests

from common import ROOT, sanitize

OUT_DIR = ROOT / "out"
CARDS_JSON = OUT_DIR / "cards.json"
SQL_PATH = OUT_DIR / "upsert.sql"

SUPABASE_URL = "https://ugpubzjcrhwlwgkfxgup.supabase.co"
ANON_KEY = ("eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVn"
            "cHViempjcmh3bHdna2Z4Z3VwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODIyNjM5NDAsImV4cCI6"
            "MjA5NzgzOTk0MH0.Z1mFomaJtw4mMnwu60-TPtxJW7n9LaNm0iOImN4o0vI")

# scraper field -> table column
COLMAP = {
    "bank": "bank_name", "name": "card_name", "network": "network",
    "network_confidence": "network_confidence", "category": "category",
    "type": "card_type", "annual_fee": "annual_fee", "joining_fee": "joining_fee",
    "fee_waiver": "fee_waiver", "forex": "forex_markup_pct",
    "finance_pm": "finance_charge_monthly_pct", "finance_pa": "finance_charge_annual_pct",
    "cash_advance": "cash_advance_fee", "cash_interest": "cash_interest",
    "late_fee": "late_payment_fee", "rewards": "reward_summary", "lounge": "lounge_access",
    "welcome_benefit": "welcome_benefit", "features": "features", "badge": "badge",
    "apply_url": "apply_url", "source_url": "source_url", "source_section": "source_section",
    "mitc_last_checked": "mitc_last_checked", "data_status": "data_status",
    "match_status": "match_status",
}


def sql_lit(v) -> str:
    if v is None or v == "":
        return "NULL"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return repr(v)
    if isinstance(v, list):
        if not v:
            return "NULL"
        inner = ",".join("'" + sanitize(str(x)).replace("'", "''") + "'" for x in v)
        return f"ARRAY[{inner}]::text[]"
    return "'" + sanitize(str(v)).replace("'", "''") + "'"


def build_rows():
    cards = json.loads(CARDS_JSON.read_text(encoding="utf-8"))
    rows = []
    for c in cards:
        rec = {"card_id": c["card_id"], "slug": c["card_id"]}
        for sk, col in COLMAP.items():
            rec[col] = c.get(sk)
        af, jf = c.get("annual_fee"), c.get("joining_fee")
        rec["is_lifetime_free"] = (af in (0, None)) and (jf in (0, None))
        rows.append(rec)
    return rows


def existing_slugs():
    r = requests.get(f"{SUPABASE_URL}/rest/v1/cards", params={"select": "slug"},
                     headers={"apikey": ANON_KEY, "Authorization": f"Bearer {ANON_KEY}"},
                     timeout=30)
    r.raise_for_status()
    return {row["slug"] for row in r.json() if row.get("slug")}


def emit_sql(rows) -> None:
    cols = ["card_id", "slug"] + list(COLMAP.values()) + ["is_lifetime_free", "updated_at"]
    set_cols = [c for c in cols if c not in ("card_id", "slug")]
    lines = ["-- Stage 7 upsert (idempotent on slug/card_id). Generated by load.py.",
             "begin;"]
    for rec in rows:
        vals = []
        for c in cols:
            vals.append("now()" if c == "updated_at" else sql_lit(rec.get(c)))
        lines.append(
            f"insert into public.cards ({', '.join(cols)}) values ({', '.join(vals)})\n"
            f"  on conflict (slug) do update set "
            + ", ".join(f"{c}=excluded.{c}" for c in set_cols) + ";")
    lines.append("commit;")
    SQL_PATH.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--report", action="store_true", help="only print counts")
    args = ap.parse_args()

    rows = build_rows()
    ids = [r["card_id"] for r in rows]
    try:
        existing = existing_slugs()
    except Exception as e:
        print(f"(could not read existing slugs: {e}); reporting totals only")
        existing = set()
    updates = [i for i in ids if i in existing]
    inserts = [i for i in ids if i not in existing]
    orphans = sorted(existing - set(ids))

    print(f"cards.json rows : {len(rows)}")
    print(f"existing in DB  : {len(existing)}")
    print(f"-> UPDATE (match): {len(updates)}  {updates if len(updates)<=12 else ''}")
    print(f"-> INSERT (new)  : {len(inserts)}")
    if orphans:
        print(f"\n!! {len(orphans)} existing rows NOT in cards.json (would remain as duplicates):")
        for o in orphans:
            print(f"     {o}")

    if not args.report:
        emit_sql(rows)
        print(f"\nWrote {SQL_PATH}  (apply via Supabase MCP / service role to perform the upsert)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
