#!/usr/bin/env python3
"""Stage 7 — upsert out/cards.json into the Supabase `cards` table.

Keyed on card_id (stored in slug/card_id, both unique) so re-runs UPDATE
instead of duplicating. The anon key is read-only, and piping ~1.3 MB of INSERTs
through the MCP is impractical, so the load happens SERVER-SIDE: Postgres fetches
the committed cards.json from the GitHub raw URL via the `http` extension and
upserts it in one statement. Orphan rows (in the DB but not in cards.json) are
deleted so the scraper stays the source of truth.

  python load.py            # report insert/update split + (re)write out/upsert.sql
  python load.py --report   # just the report

Apply the emitted out/upsert.sql with elevated access (Supabase MCP / service
role). NOTE: it loads from GitHub `main`, so commit + push cards.json first.
"""
from __future__ import annotations
import argparse
import json
import sys

import requests

from common import ROOT

OUT_DIR = ROOT / "out"
CARDS_JSON = OUT_DIR / "cards.json"
SQL_PATH = OUT_DIR / "upsert.sql"

RAW_URL = "https://raw.githubusercontent.com/rjkmrdesai/card-gyani/main/scraper/out/cards.json"
SUPABASE_URL = "https://ugpubzjcrhwlwgkfxgup.supabase.co"
ANON_KEY = ("eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVn"
            "cHViempjcmh3bHdna2Z4Z3VwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODIyNjM5NDAsImV4cCI6"
            "MjA5NzgzOTk0MH0.Z1mFomaJtw4mMnwu60-TPtxJW7n9LaNm0iOImN4o0vI")

# JSON key -> table column (jsonb_to_recordset does the heavy lifting in SQL)
COLS = [  # (json_key, recordset_type, table_column, select_expr)
    ("card_id", "text", "card_id", "card_id"),
    ("card_id", None, "slug", "card_id"),
    ("bank", "text", "bank_name", "bank"),
    ("name", "text", "card_name", "coalesce(name, card_id)"),   # card_name is NOT NULL
    ("network", "text", "network", "network"),
    ("network_confidence", "text", "network_confidence", "network_confidence"),
    ("category", "text", "category", "category"),
    ("type", "text", "card_type", "type"),
    ("annual_fee", "numeric", "annual_fee", "annual_fee"),
    ("joining_fee", "numeric", "joining_fee", "joining_fee"),
    ("fee_waiver", "text", "fee_waiver", "fee_waiver"),
    ("forex", "numeric", "forex_markup_pct", "forex"),
    ("finance_pm", "numeric", "finance_charge_monthly_pct", "finance_pm"),
    ("finance_pa", "numeric", "finance_charge_annual_pct", "finance_pa"),
    ("cash_advance", "text", "cash_advance_fee", "cash_advance"),
    ("cash_interest", "text", "cash_interest", "cash_interest"),
    ("late_fee", "text", "late_payment_fee", "late_fee"),
    ("rewards", "text", "reward_summary", "rewards"),
    ("lounge", "text", "lounge_access", "lounge"),
    ("welcome_benefit", "text", "welcome_benefit", "welcome_benefit"),
    ("features", "jsonb", "features",
     "case when features is null then null else array(select jsonb_array_elements_text(features)) end"),
    ("badge", "text", "badge", "badge"),
    ("apply_url", "text", "apply_url", "apply_url"),
    ("source_url", "text", "source_url", "source_url"),
    ("source_section", "text", "source_section", "source_section"),
    ("match_status", "text", "match_status", "match_status"),
    ("mitc_last_checked", "date", "mitc_last_checked", "mitc_last_checked"),
    ("data_status", "text", "data_status", "data_status"),
    (None, None, "is_lifetime_free", "(coalesce(annual_fee,0)=0 and coalesce(joining_fee,0)=0)"),
    (None, None, "updated_at", "now()"),
]


def recordset_def():
    seen, parts = set(), []
    for key, typ, _, _ in COLS:
        if key and typ and key not in seen:
            seen.add(key); parts.append(f"{key} {typ}")
    return ", ".join(parts)


def emit_sql(orphans):
    table_cols = [c[2] for c in COLS]
    select_exprs = [c[3] for c in COLS]
    set_cols = [c for c in table_cols if c not in ("card_id", "slug")]
    orphan_clause = ("'" + "','".join(orphans) + "'") if orphans else "''"
    sql = f"""-- Stage 7 load (idempotent on slug/card_id). Generated by load.py.
-- Loads cards.json from GitHub server-side, so commit + push it first.
create extension if not exists http with schema extensions;
with j as (
  select (extensions.http_get('{RAW_URL}')).content::jsonb as data
),
src as (
  select x.* from j, jsonb_to_recordset(j.data) as x({recordset_def()})
),
del as (
  delete from public.cards where slug in ({orphan_clause}) returning 1
),
up as (
  insert into public.cards ({', '.join(table_cols)})
  select {', '.join(select_exprs)} from src
  on conflict (slug) do update set
    {', '.join(f'{c}=excluded.{c}' for c in set_cols)}
  returning (xmax = 0) as inserted
)
select (select count(*) from del) as deleted_orphans,
       count(*) filter (where inserted) as inserted,
       count(*) filter (where not inserted) as updated
from up;
"""
    SQL_PATH.write_text(sql, encoding="utf-8")


def existing_slugs():
    r = requests.get(f"{SUPABASE_URL}/rest/v1/cards", params={"select": "slug"},
                     headers={"apikey": ANON_KEY, "Authorization": f"Bearer {ANON_KEY}"},
                     timeout=30)
    r.raise_for_status()
    return {row["slug"] for row in r.json() if row.get("slug")}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--report", action="store_true")
    args = ap.parse_args()

    ids = {c["card_id"] for c in json.loads(CARDS_JSON.read_text(encoding="utf-8"))}
    try:
        existing = existing_slugs()
    except Exception as e:
        print(f"(could not read existing slugs: {e})"); existing = set()
    updates = sorted(ids & existing)
    inserts = ids - existing
    orphans = sorted(existing - ids)

    print(f"cards.json rows : {len(ids)}")
    print(f"existing in DB  : {len(existing)}")
    print(f"-> UPDATE (slug match): {len(updates)}")
    print(f"-> INSERT (new)       : {len(inserts)}")
    print(f"-> DELETE (orphans)   : {len(orphans)} {orphans if orphans else ''}")

    if not args.report:
        emit_sql(orphans)
        print(f"\nWrote {SQL_PATH} (apply via Supabase MCP / service role).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
